package_name = "curl"
repo_path = "https://dl-cdn.alpinelinux.org/alpine/latest-stable/main/x86_64/APKINDEX.tar.gz"
repo_mode = "remote"
output_file = "graph.dot"
ascii_mode = false
max_depth = 1
filter_substring = ""
